---
- name: installtion of java, docker and jenkins
  become: yes
  hosts: localhost
  tasks:
  - name: installing docker
    apt:
      name: docker.io
      state: latest
      update_cache: yes
  - name: instaling java
    apt:
      name: openjdk-17-jdk
      state: latest
      update_cache: yes
  - name: jenkins installing
    script: script.sh
